server:
  port: 9033  # Puerto fijo para la aplicación
spring:
  application:
    name: msvc-usuario
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://soa.c904q64o6yfq.us-east-2.rds.amazonaws.com:5432/soa  # Nueva URL de la base de datos
    username: postgres  # Nuevo usuario
    password: admin123  # Nueva contraseña

  jpa:
    hibernate:
      ddl-auto: update
    database: soa
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/