server:
  port: 0  # Puerto din치mico para que Docker asigne autom치ticamente el puerto

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/microservice-soa-db  # Nombre del servicio de Postgres en Docker
    username: microservice-soa
    password: kiones

  jpa:
    hibernate:
      ddl-auto: update  # Actualizaci칩n autom치tica de tablas durante el desarrollo
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
