server:
  port: 9030  # Puerto fijo para la aplicación
spring:
  application:
    name: msvc-usuario
  config:
    import: "classpath:/config/common.yml"

  jpa:
    hibernate:
      ddl-auto: update    
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/