spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Habilita la resolución dinámica con Eureka
      routes:
        - id: productos-service
          uri: lb://producto-categoria-service  # Nombre registrado en Eureka
          predicates:
            - Path=/api/productos/**
        - id: categorias-service
          uri: lb://producto-categoria-service
          predicates:
            - Path=/api/categorias/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true  # Usa la IP del contenedor en lugar del nombre de host
