spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # Convertir los IDs de servicio a minúsculas
      routes:
        - id: producto-categoria-service # ID del servicio en docker-compose.yml
          uri: lb://producto-categoria-service # Usar balanceador de carga
          predicates:
            - Path=/api/productos/**
            - Path=/api/categorias/**
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/usuarios/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: correo-service
          uri: lb://correo-service
          predicates:
           - Path=/enviar-correo/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/ # Usar el nombre del servicio de Eureka en docker-compose