spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Habilita la resolución dinámica a través de Eureka
      routes:
        - id: producto-service
          uri: lb://producto-service  # Load Balancer URI apuntando al servicio
          predicates:
            - Path=/api/productos/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true  # Usa la dirección IP en lugar del nombre de host