server:
  port: 8040  # Puerto fijo para la aplicación
spring:
  application:
    name: msvc-producto-categoria
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/microservice-soa-db  # Usamos el nombre del contenedor en lugar de localhost
    username: microservice-soa
    password: kiones

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/