spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: productos
          uri: lb://producto-categoria-service
          predicates:
            - Path=/api/productos/**
eureka:
  client:
    register-with-eureka: false