server:
  port: 8761  # Puerto en el que correrá Eureka

spring:
  application:
    name: msvc-eureka  # Nombre del servicio en Eureka

eureka:
  client:
    register-with-eureka: false  # El servidor Eureka no se registra en sí mismo
    fetch-registry: false        # No obtiene el registro de otros servicios, ya que es el servidor central

logging:
  level:
    root: INFO
    com.netflix.eureka: DEBUG  # Nivel de logging para Eureka
