server:
  port: 0  # Puerto dinámico para que Docker asigne automáticamente el puerto


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/  # Conexión al Eureka Server